version: "3"

services:
  squad-maprota-generator:
    container_name: squad-maprota-generator
    image: ghcr.io/welovesquad/squadmaprotagenerator:latest
    restart: "no"
    volumes:
      - "./output:/home/node/app/output:rw"
      - "./config.json:/home/node/app/config.json:ro"
