version: "3"
services:
  squad-maprota-generator:
    container_name: squad-maprota-generator
    image: ghcr.io/welovesquad/squadmaprotagenerator:latest
    ports:
      - "69247:69247"
    restart: always
    volumes:
      - "./config.json:/etc/maprota/config.json:ro"
