name: Docker test run

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build image
        run: docker build -t welovesquad/squadmaprotagenerator:latest .
      -
        name: Run the released image with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: welovesquad/squadmaprotagenerator:latest
